<!--
/*
 * Gamuza Itau ShopLine - Itau ShopLine for Magento platform.
 * Copyright (C) 2013 Gamuza Technologies (http://www.gamuza.com.br/)
 * Author: Eneias Ramos de Melo <eneias@gamuza.com.br>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

/*
 * See the AUTHORS file for a list of people on the Gamuza Team.
 * See the ChangeLog files for a list of changes.
 * These files are distributed with Gamuza_Itaushopline at http://code.google.com/p/gamuzaopen/.
 */
-->

<p><strong><?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?></strong></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
    <tbody>
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <tr>
            <td><strong><?php echo $this->escapeHtml($_label)?>:</strong></td>
            <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif;?>

<?php
$controllerName = Mage::app ()->getRequest ()->getControllerName ();
$moduleName = Mage::app ()->getRequest ()->getModuleName ();

$isValidCheckout = !strcmp ($controllerName, 'onepage') || !strcmp ($moduleName, 'onestepcheckout') ? true : false;
?>

<?php if ($isValidCheckout): ?>
<?php
$popUpAlert1 = $this->helper ('itaushopline')->__("Hmmm... We found a pop-up blocker in your web browser.");
$popUpAlert2 = $this->helper ('itaushopline')->__("Please disable your pop-up blocker for this site and click on 'Submit' link again.");
?>

<script type="text/javascript">
function GamuzaPaymentPopup (form)
{
    popUp = window.open ("", 'gamuza_payment_popup');
    if (popUp == null || typeof (popUp) == 'undefined')
    {
        alert("<?php echo $popUpAlert1; ?>" + '\n' + "<?php echo $popUpAlert2; ?>");
        
        return false;
    }
    else
    {
        form.target = 'gamuza_payment_popup';
        popUp.focus ();
        
        return true;
    }
}
</script>
<?php endif; ?>

<?php
$submitType = Mage::getStoreConfig ('payment/itaushopline_settings/submit_type');
$submitForm = $isValidCheckout && !strcmp ($submitType, '1') ? 'onSubmit="GamuzaPaymentPopup (this);"' : 'target="_blank"';
?>

<form method="post" id="itaushopline_form_submit" action="<?php echo $this->_getStoreConfig ('submit_url'); ?>" <?php echo $submitForm; ?>>
<?php echo $this->getSubmitTransactionInformation (); ?>
</form>

<?php if ($isValidCheckout): ?>
<script type="text/javascript">
Event.observe (window, "load", function (){
$('itaushopline_form_submit').submit.click ();
});
</script>
<?php endif; ?>

<?php echo $this->getChildHtml()?>

